// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface BidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companySymbol = 1;</code>
   * @return The companySymbol.
   */
  java.lang.String getCompanySymbol();
  /**
   * <code>string companySymbol = 1;</code>
   * @return The bytes for companySymbol.
   */
  com.google.protobuf.ByteString
      getCompanySymbolBytes();

  /**
   * <code>int32 numberOfOffers = 2;</code>
   * @return The numberOfOffers.
   */
  int getNumberOfOffers();
}
