// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface CompanySharesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CompanySharesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companySymbol = 1;</code>
   * @return The companySymbol.
   */
  java.lang.String getCompanySymbol();
  /**
   * <code>string companySymbol = 1;</code>
   * @return The bytes for companySymbol.
   */
  com.google.protobuf.ByteString
      getCompanySymbolBytes();

  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
