// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface GenerateClientIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateClientIdRequest)
    com.google.protobuf.MessageOrBuilder {
}
