// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface GenerateClientIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateClientIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 balance = 3;</code>
   * @return The balance.
   */
  int getBalance();
}
