// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buyOrSell = 1;</code>
   * @return The buyOrSell.
   */
  java.lang.String getBuyOrSell();
  /**
   * <code>string buyOrSell = 1;</code>
   * @return The bytes for buyOrSell.
   */
  com.google.protobuf.ByteString
      getBuyOrSellBytes();

  /**
   * <code>string companySymbol = 2;</code>
   * @return The companySymbol.
   */
  java.lang.String getCompanySymbol();
  /**
   * <code>string companySymbol = 2;</code>
   * @return The bytes for companySymbol.
   */
  com.google.protobuf.ByteString
      getCompanySymbolBytes();

  /**
   * <code>double pricePerShare = 3;</code>
   * @return The pricePerShare.
   */
  double getPricePerShare();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string clientId = 5;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 5;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
