// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface SellRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SellRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companySymbol = 1;</code>
   * @return The companySymbol.
   */
  java.lang.String getCompanySymbol();
  /**
   * <code>string companySymbol = 1;</code>
   * @return The bytes for companySymbol.
   */
  com.google.protobuf.ByteString
      getCompanySymbolBytes();

  /**
   * <code>double pricePerShare = 2;</code>
   * @return The pricePerShare.
   */
  double getPricePerShare();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
