// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public final class Stockexchange {
  private Stockexchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowedSymbolsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowedSymbolsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateClientIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateClientIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateClientIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateClientIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023stockexchange.proto\"]\n\tStockData\022\016\n\006sy" +
      "mbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\r\n\005price" +
      "\030\003 \001(\001\022\016\n\006change\030\004 \001(\001\022\014\n\004date\030\005 \001(\t\")\n\014" +
      "StockRequest\022\031\n\021numberOfCompanies\030d \001(\005\"" +
      ")\n\026FollowedSymbolsRequest\022\017\n\007symbols\030\001 \003" +
      "(\t\";\n\nAskRequest\022\025\n\rcompanySymbol\030\001 \001(\t\022" +
      "\026\n\016numberOfOffers\030\002 \001(\005\";\n\nBidRequest\022\025\n" +
      "\rcompanySymbol\030\001 \001(\t\022\026\n\016numberOfOffers\030\002" +
      " \001(\005\",\n\tSellOffer\022\r\n\005price\030\001 \001(\001\022\020\n\010quan" +
      "tity\030\002 \001(\005\"+\n\010BuyOffer\022\r\n\005price\030\001 \001(\001\022\020\n" +
      "\010quantity\030\002 \001(\005\"^\n\nBuyRequest\022\025\n\rcompany" +
      "Symbol\030\001 \001(\t\022\025\n\rpricePerShare\030\002 \001(\001\022\020\n\010q" +
      "uantity\030\003 \001(\005\022\020\n\010clientId\030\004 \001(\t\"/\n\013BuyRe" +
      "sponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t" +
      "\"_\n\013SellRequest\022\025\n\rcompanySymbol\030\001 \001(\t\022\025" +
      "\n\rpricePerShare\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\022" +
      "\020\n\010clientId\030\004 \001(\t\"0\n\014SellResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"s\n\014OrderRequ" +
      "est\022\021\n\tbuyOrSell\030\001 \001(\t\022\025\n\rcompanySymbol\030" +
      "\002 \001(\t\022\025\n\rpricePerShare\030\003 \001(\001\022\020\n\010quantity" +
      "\030\004 \001(\005\022\020\n\010clientId\030\005 \001(\t\"1\n\rOrderRespons" +
      "e\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\031\n\027G" +
      "enerateClientIdRequest\"N\n\030GenerateClient" +
      "IdResponse\022\020\n\010clientId\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t\022\017\n\007balance\030\003 \001(\0052\226\003\n\024StockExchange" +
      "Service\022-\n\014getStockData\022\r.StockRequest\032\n" +
      ".StockData\"\0000\001\022@\n\025updateFollowedSymbols\022" +
      "\027.FollowedSymbolsRequest\032\n.StockData\"\0000\001" +
      "\022\"\n\003Ask\022\013.AskRequest\032\n.SellOffer\"\0000\001\022!\n\003" +
      "Bid\022\013.BidRequest\032\t.BuyOffer\"\0000\001\022\"\n\003buy\022\013" +
      ".BuyRequest\032\014.BuyResponse\"\000\022%\n\004sell\022\014.Se" +
      "llRequest\032\r.SellResponse\"\000\022.\n\013submitOrde" +
      "r\022\r.OrderRequest\032\016.OrderResponse\"\000\022K\n\020ge" +
      "nerateClientId\022\030.GenerateClientIdRequest" +
      "\032\031.GenerateClientIdResponse\"\0000\001B\031\n\025rs.ra" +
      "f.pds.v5.z2.gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StockData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockData_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "Price", "Change", "Date", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "NumberOfCompanies", });
    internal_static_FollowedSymbolsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FollowedSymbolsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowedSymbolsRequest_descriptor,
        new java.lang.String[] { "Symbols", });
    internal_static_AskRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskRequest_descriptor,
        new java.lang.String[] { "CompanySymbol", "NumberOfOffers", });
    internal_static_BidRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_descriptor,
        new java.lang.String[] { "CompanySymbol", "NumberOfOffers", });
    internal_static_SellOffer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SellOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellOffer_descriptor,
        new java.lang.String[] { "Price", "Quantity", });
    internal_static_BuyOffer_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_BuyOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyOffer_descriptor,
        new java.lang.String[] { "Price", "Quantity", });
    internal_static_BuyRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_BuyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyRequest_descriptor,
        new java.lang.String[] { "CompanySymbol", "PricePerShare", "Quantity", "ClientId", });
    internal_static_BuyResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_BuyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_SellRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SellRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellRequest_descriptor,
        new java.lang.String[] { "CompanySymbol", "PricePerShare", "Quantity", "ClientId", });
    internal_static_SellResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_SellResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "BuyOrSell", "CompanySymbol", "PricePerShare", "Quantity", "ClientId", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_GenerateClientIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_GenerateClientIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateClientIdRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GenerateClientIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_GenerateClientIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateClientIdResponse_descriptor,
        new java.lang.String[] { "ClientId", "Message", "Balance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
