// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public final class Stockexchange {
  private Stockexchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowedSymbolsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowedSymbolsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023stockexchange.proto\"]\n\tStockData\022\016\n\006sy" +
      "mbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\r\n\005price" +
      "\030\003 \001(\001\022\016\n\006change\030\004 \001(\001\022\014\n\004date\030\005 \001(\t\")\n\014" +
      "StockRequest\022\031\n\021numberOfCompanies\030d \001(\005\"" +
      ")\n\026FollowedSymbolsRequest\022\017\n\007symbols\030\001 \003" +
      "(\t2\207\001\n\024StockExchangeService\022-\n\014getStockD" +
      "ata\022\r.StockRequest\032\n.StockData\"\0000\001\022@\n\025up" +
      "dateFollowedSymbols\022\027.FollowedSymbolsReq" +
      "uest\032\n.StockData\"\0000\001B\031\n\025rs.raf.pds.v5.z2" +
      ".gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StockData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockData_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "Price", "Change", "Date", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "NumberOfCompanies", });
    internal_static_FollowedSymbolsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FollowedSymbolsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowedSymbolsRequest_descriptor,
        new java.lang.String[] { "Symbols", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
