// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface StockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberOfCompanies = 100;</code>
   * @return The numberOfCompanies.
   */
  int getNumberOfCompanies();
}
