// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockexchange.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TradingTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TradingTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buyerClientId = 1;</code>
   * @return The buyerClientId.
   */
  java.lang.String getBuyerClientId();
  /**
   * <code>string buyerClientId = 1;</code>
   * @return The bytes for buyerClientId.
   */
  com.google.protobuf.ByteString
      getBuyerClientIdBytes();

  /**
   * <code>string sellerClientId = 2;</code>
   * @return The sellerClientId.
   */
  java.lang.String getSellerClientId();
  /**
   * <code>string sellerClientId = 2;</code>
   * @return The bytes for sellerClientId.
   */
  com.google.protobuf.ByteString
      getSellerClientIdBytes();

  /**
   * <code>string companySymbol = 3;</code>
   * @return The companySymbol.
   */
  java.lang.String getCompanySymbol();
  /**
   * <code>string companySymbol = 3;</code>
   * @return The bytes for companySymbol.
   */
  com.google.protobuf.ByteString
      getCompanySymbolBytes();

  /**
   * <code>double pricePerShare = 4;</code>
   * @return The pricePerShare.
   */
  double getPricePerShare();

  /**
   * <code>int32 quantity = 5;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string date = 6;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 6;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
